"""Schema-conformance assertions for emitted records.

Implements `cpt-insightspec-dod-cn-mock-schema-conformance`: every emitted
record must validate against the stream's JSON schema, and must not carry
fields the schema does not declare (manifest<->schema drift), regardless of the
schema's own `additionalProperties` (which is `true` in production so Airbyte
tolerates source-side additions).

Schema resolution order:
1. `<package>/schemas/<stream>.json` (generated by generate-schema.sh)
2. the stream's InlineSchemaLoader schema in connector.yaml
"""

from __future__ import annotations

import json
from typing import Any

from jsonschema import Draft7Validator

from connector_tests.source import connector_dir, load_manifest


def stream_schema(connector_path: str, stream: str) -> dict[str, Any]:
    schema_file = connector_dir(connector_path) / "schemas" / f"{stream}.json"
    if schema_file.is_file():
        with open(schema_file) as f:
            return json.load(f)
    for s in load_manifest(connector_path).get("streams", []):
        if s.get("name") == stream:
            loader = s.get("schema_loader") or {}
            if loader.get("type") == "InlineSchemaLoader":
                return loader["schema"]
            raise ValueError(
                f"stream '{stream}' has no schemas/{stream}.json and no "
                f"InlineSchemaLoader schema (loader: {loader.get('type')})"
            )
    raise ValueError(f"stream '{stream}' not found in {connector_path} connector.yaml")


def assert_records_conform(
    records: list[Any], connector_path: str, stream: str, strict: bool = True
) -> None:
    """Validate every record against the stream schema.

    `records` accepts the `output.records` list from a protocol read (items
    with `.record.data`) or plain dicts.

    With `strict=True` (default) a record key the schema does not declare fails
    the assertion — this catches manifest<->schema drift (an AddFields output
    missing from the inline schema) that production tolerates via
    `additionalProperties: true`. Pass `strict=False` for streams that
    intentionally pass through undeclared transport fields from the source API
    (e.g. jira_issue_keys keeps the raw `fields` object).
    """
    schema = stream_schema(connector_path, stream)
    validator = Draft7Validator(schema)
    declared = set(schema.get("properties", {}).keys())
    problems: list[str] = []
    for i, item in enumerate(records):
        data = item if isinstance(item, dict) else item.record.data
        for err in validator.iter_errors(data):
            path = ".".join(str(p) for p in err.absolute_path) or "<record>"
            problems.append(f"record[{i}] {stream}.{path}: {err.message}")
        if strict and declared:
            for key in data.keys() - declared:
                problems.append(
                    f"record[{i}] {stream}.{key}: field not declared in the stream schema"
                )
    if problems:
        raise AssertionError(
            f"{len(problems)} schema violation(s) for stream '{stream}':\n  "
            + "\n  ".join(sorted(problems)[:20])
        )
